# Generated by Django 5.1.3 on 2025-03-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_other_field_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='partial_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
