# Generated by Django 5.1.3 on 2025-03-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_paid_amount_booking_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='remaining_balance',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_payment_amount',
        ),
    ]
