# Generated by Django 5.1.3 on 2025-01-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionproject',
            name='client_name',
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='description',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
